name: d2scf

on:
#   schedule:
#     - cron: '30 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.USER }}/${{ secrets.CO_REP }}
          ref: ${{ secrets.D_BRA_HW }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install env
        run: |
          npm install
          npm install tencentcloud-sdk-nodejs
          npm install js-yaml
# 
      - name: Replace
        run: |
          wget https://raw.githubusercontent.com/${{ secrets.USER }}/${{ secrets.CO_REP_AC }}/main/replace.sh
          sh replace.sh

      - name: Zip dir
        run: |
          rm -rf activity/ backUp/ docker/ icon/
          zip -r myfile.zip ./*
          ls -lh myfile.zip

      - name: Deploy
        run: |
          node tencentscf.js
          env
        env:
          STAGE: dev
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          TENCENT_REGION: ${{ secrets.SCF_REGION }}
          TENCENT_FUNCTION_NAME: ${{ secrets.TENCENT_FUNCTION_NAME }}
          SCF_REGION: ${{ secrets.SCF_REGION }}
          JD_COOKIE: ${{ secrets.JD_COOKIE}}
          PUSH_KEY: ${{ secrets.PUSH_KEY}}
          QYWX_AM: ${{ secrets.QYWX_AM}}
          MARKET_COIN_TO_BEANS: ${{ secrets.MARKET_COIN_TO_BEANS}}
          FRUIT_BEAN_CARD: ${{ secrets.FRUIT_BEAN_CARD}}
          HELP_AUTHOR: ${{ secrets.HELP_AUTHOR}}        
# 
      - name: Replace SL
        run: |
          wget https://raw.githubusercontent.com/${{ secrets.USER }}/${{ secrets.CO_REP_AC }}/main/replace_SL.sh
          sh replace_SL.sh

      - name: Zip dir SL
        run: |
          rm -rf activity/ backUp/ docker/ icon/
          zip -r myfile.zip ./*
          ls -lh myfile.zip

      - name: Deploy SL
        run: node tencentscf.js
        env:
          STAGE: dev
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          TENCENT_REGION: ${{ secrets.SCF_REGION }}
          TENCENT_FUNCTION_NAME: ${{ secrets.TENCENT_FUNCTION_NAME_SL }}
          SCF_REGION: ${{ secrets.SCF_REGION }}
          JD_COOKIE: ${{ secrets.JD_COOKIE}}
          PUSH_KEY: ${{ secrets.PUSH_KEY}}
          QYWX_AM: ${{ secrets.QYWX_AM}}
          MARKET_COIN_TO_BEANS: ${{ secrets.MARKET_COIN_TO_BEANS}}
          FRUIT_BEAN_CARD: ${{ secrets.FRUIT_BEAN_CARD}}
          HELP_AUTHOR: ${{ secrets.HELP_AUTHOR}}   
