name: d2scf

on:
#   schedule:
#     - cron: '30 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.D_REP_JS}}
          ref: ${{ secrets.D_BRA_HW}}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install env
        run: |
          npm install
          npm install tencentcloud-sdk-nodejs
          npm install js-yaml
# 
      - name: Replace
        run: |
          wget https://raw.githubusercontent.com/${{ secrets.D_REP_JS}}/${{ secrets.D_BRA_HW}}/replace.sh
          sh replace.sh

      - name: Zip dir
        run: |
          rm -rf activity/ backUp/ docker/ icon/
          zip -r myfile.zip ./*
          ls -lh myfile.zip

      - name: Deploy
        run: node tencentscf.js
# 
      - name: Replace SL
        run: |
          wget https://raw.githubusercontent.com/${{ secrets.D_REP_JS}}/${{ secrets.D_BRA_HW}}/replace_SL.sh
          sh replace_SL.sh

      - name: Zip dir SL
        run: |
          rm -rf activity/ backUp/ docker/ icon/
          zip -r myfile.zip ./*
          ls -lh myfile.zip

      - name: Deploy SL
        run: node tencentscf.js
