name: sync-HW
on:
  schedule:
    - cron: '11 */4 * * *'
  workflow_dispatch:
#   watch:
#     types: started
#   push:
#     branches: [ master ]
  repository_dispatch:
    types: sync-HW
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ secrets.S_REP_HW }}
          source_branch: ${{ secrets.S_BRA_HW }}
          destination_repo: ${{ secrets.D_REP_HW }}
          destination_branch: ${{ secrets.D_BRA_HW }}
#           ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
#           source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.TOKEN }} # optional, will override `SSH_PRIVATE_KEY`          
